version: '3.5'
services:
  db:
    image: postgres:12.0-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=9mREavXDs9Gk89Ef
      - POSTGRES_DB=app
      - POSTGRES_USER=app